name: Java CI with Maven

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        java-version: [ '17' ]
        os: [ 'ubuntu-latest' ]

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java-version }}
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -f ./estelar/pom.xml clean package

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4
      with:
    # Artifact name
        name: estelar_artifact
    # A file, directory or wildcard pattern that describes what to upload
        path: ./target

  deploy-lambda:
    needs: build
    uses: ./.github/workflows/Lambda.yml
    secrets: inherit